"use client";

import Link from "next/link";
import './globals.css';
import { useEffect, useState } from "react";

// export const metadata = {
//   title: "Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [topics, setTopics] = useState([]);
  // 서버에서 클라리언트로 데이터를 가져온다. 만약 서버에서 데이터를 가져오는데 시간이 걸린다면, 상당한 비효율을 가져온다.
  // 또한 javascript 를 중지하면, fetch 한 데이터는 안가져온다.
  useEffect(() => {
    fetch('http://localhost:9999/topics')
    .then(res => res.json())
    .then(data => setTopics(data));
  }, []);

  return (
    <html>
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map(topic => {
            return (
              <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
            )
          })}
          {/* <li><Link href="/read/1">html</Link></li>
          <li><Link href="/read/2">css</Link></li> */}
        </ol>
        {children}
        <ul>
          <li><Link href="/create">create</Link></li>
          <li><Link href="/update/1">update</Link></li>
          <li><input type="button" value="delete"></input></li>
        </ul>
      </body>
    </html>
  );
}
